import {
  PayCircleOutlined,
  ShoppingCartOutlined,
  MessageOutlined,
  TeamOutlined,
  UserOutlined,
  DashboardOutlined,
  ApiOutlined,
  CameraOutlined,
  EditOutlined,
  CodeOutlined,
  LineOutlined,
  BarChartOutlined,
  AreaChartOutlined,
  HomeOutlined,
  AppstoreOutlined,
  FileDoneOutlined,
  TrophyOutlined,
  StockOutlined,
  ReadOutlined, SettingOutlined, OrderedListOutlined, TagsOutlined, PlusSquareOutlined, NotificationOutlined
} from '@ant-design/icons'
import Setting from "../pages/common/setting/Setting";

const iconMap: { [key: string]: any } = {
  'pay-circle-o': <PayCircleOutlined/>,
  'shopping-cart': <ShoppingCartOutlined/>,
  'camera-o': <CameraOutlined/>,
  'line-chart': <LineOutlined/>,
  'code-o': <CodeOutlined/>,
  'area-chart': <AreaChartOutlined/>,
  'bar-chart': <BarChartOutlined/>,
  message: <MessageOutlined/>,
  team: <TeamOutlined/>,
  dashboard: <DashboardOutlined/>,
  user: <UserOutlined/>,
  api: <ApiOutlined/>,
  edit: <EditOutlined/>,
  home: <HomeOutlined/>,
  appstore: <AppstoreOutlined/>,
  fileDone: <FileDoneOutlined/>,
  trophy: <TrophyOutlined/>,
  stock: <StockOutlined/>,
  read: <ReadOutlined/>,
  setting: <SettingOutlined/>,
  list: <OrderedListOutlined/>,
  tags:<TagsOutlined />,
  add: <PlusSquareOutlined />,
  notice:<NotificationOutlined />,
}
export default iconMap
// export default {
//   'pay-circle-o': <PayCircleOutlined />,
//   'shopping-cart': <ShoppingCartOutlined />,
//   'camera-o': <CameraOutlined />,
//   'line-chart': <LineOutlined />,
//   'code-o': <CodeOutlined />,
//   'area-chart': <AreaChartOutlined />,
//   'bar-chart': <BarChartOutlined />,
//   message: <MessageOutlined />,
//   team: <TeamOutlined />,
//   dashboard: <DashboardOutlined />,
//   antdUser: <UserOutlined />,
//   api: <ApiOutlined />,
//   edit: <EditOutlined />,
// }
